### ISSUE TITLE
Adding args disables prettier pre-commit hook

### ISSUE THREAD

**Issue by elhachimi** [awebdeveloper/pre-commit-prettier#1]
Adding an argument this way:
```
-   repo: git://github.com/awebdeveloper/pre-commit-prettier
    sha: v0.0.1
    hooks:
    -   id: prettier
        additional_dependencies: ['prettier@1.4.2']
        args: ['--single-quote']
```

the prettier hook passes but the committed files doesn't change

**Comment by amonks** [comment]
I'm actually seeing that same behaviour _without_ specifying any args. The hook passes whether or not my staged files conform to prettier formatting.

**Comment by elhachimi** [comment]
what i did is forked the repo and added the args i needed here https://github.com/awebdeveloper/pre-commit-prettier/blob/master/.pre-commit-hooks.yaml#L6
then referenced my repo in the pre-commit file with the appropriate commit sha

**Comment by amonks** [comment]
I made a test case to show the problem more clearly:

https://github.com/amonks/pre-commit-prettier-test-case

As you can see, there's a poorly-formatted javascript file, and the pre-commit-config passes args.

If you run pre-commit, pre-commit-prettier will _pass_, making no changes, despite the poorly-formatted file. Remove the args array and it works fine.

**Comment by elhachimi** [comment]
@amonks you didn't add the `'--write'` argument at the end this is why the test file doesn't change
with it it seems to work fine

**Comment by amonks** [comment]
You're right!

I assumed it would come in from the .pre-commit-hooks file in this repo or something.

**Comment by asottile** [comment]
I've fixed this in prettier's metadata: https://github.com/prettier/prettier/blob/19cd7d32278e0bc6ddab92e8c23bb8f682fa691f/.pre-commit-hooks.yaml#L3

Now specifying `args: [...]` will continue to have `--write`

**Comment by pocc** [comment]
It looks like this issue has been addressed. Can relevant parties please close?
